const gameState = {
  ageDecks: {
    age1: [],
    age2: [],
    age3: [],
    age4: [],
    age5: [],
    age6: [],
    age7: [],
    age8: [],
    age9: [],
    age10: [],
  },
  leadershipDeck: [],
  specialDeck: [],
  players: [],
  currentPlayer: null,
  activePlayer: null,
  player0: {
    name: null,
    id: 0,
    actionPoints: 0,
    hand: [],
    activeDecks: {
      red: [],
      green: [],
      blue: [],
      purple: [],
      yellow: [],
    },
  },
  player1: {
    name: null,
    id: 1,
    actionPoints: 0,
    hand: [],
    activeDecks: {
      red: [],
      green: [],
      blue: [],
      purple: [],
      yellow: [],
    },
  },
  player2: {
    name: null,
    id: 2,
    actionPoints: 0,
    hand: [],
    activeDecks: {
      red: [],
      green: [],
      blue: [],
      purple: [],
      yellow: [],
    },
  },
  player3: {
    name: null,
    id: 3,
    actionPoints: 0,
    hand: [],
    activeDecks: {
      red: [],
      green: [],
      blue: [],
      purple: [],
      yellow: [],
    },
  },
};
export default gameState;
